### ISSUE TITLE
Crashes after making projectile

### ISSUE THREAD

**Issue by TheBusinessPyro** [millefoleon/BloonTowerMaker#11]
more specifically when i make a projectile, and then open the thing with all the tower properties, it crashes with this error
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BloonTowerMaker.PathEdit.PathEdit_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by TheBusinessPyro** [comment]
I have a base tower of dartmonkey in the primary section

**Comment by TheBusinessPyro** [comment]
Also tried to make a new tower, throws out the same error. I have made a save of the tower before making a projectile

**Comment by TheBusinessPyro** [comment]
i fixed it by deleting the save but im leaving this here so it can be fixed in a future update
