### ISSUE TITLE
Throws errors everywhere after making a single projectile

### ISSUE THREAD

**Issue by TheBusinessPyro** [millefoleon/BloonTowerMaker#18]
After making a projectile and naming it, scrolling up gives it an error, press continue, close the tab, open another path, another error but this time happens on click of the path of choice. You get the point. Also doesnt save them after choosing a projectile and quitting out of the path editor tab.

**Comment by TheBusinessPyro** [comment]
These happen on ALMOST EVERY POSSIBLE ON SCREEN BUTTON

**Comment by TheBusinessPyro** [comment]
************* Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BloonTowerMaker.Data.DictionaryExtensions.RenameKey[TKey,TValue](IDictionary`2 dic, TKey fromKey, TKey toKey)
   at BloonTowerMaker.ProjectileEditor.dataGridProjectile_CellValueChanged(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellValueChanged(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellValueChangedInternal(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridViewCell.SetValue(Int32 rowIndex, Object value)
   at System.Windows.Forms.DataGridView.PushFormattedValue(DataGridViewCell& dataGridViewCurrentCell, Object formattedValue, Exception& exception)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewCell& dataGridViewCurrentCell, DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave)
   at System.Windows.Forms.DataGridView.CommitEdit(DataGridViewDataErrorContexts context, Boolean forCurrentCellChange, Boolean forCurrentRowChange)
   at System.Windows.Forms.DataGridView.OnMouseWheel(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseWheel(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by TheBusinessPyro** [comment]
When I delete the projectile, everything works now
